Remove -U/--update flag
The self-updating feature has been removed in favor of using git pull
for cloned repositories and package managers for installed packages.
This simplifies maintenance for fork users.

Changes:
- Remove -U/--update option from help and argument parsing
- Archive update_script() as _update_script_deprecated() for reference
- Remove patch from optional dependencies
- Update all documentation (INSTALL.md, man page, bug template, fork-merge.md)
- Bump version to 4.10.5

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-version_number="4.10.4"
+version_number="4.10.5"
 
 # UI
 
@@ -83,8 +83,6 @@ help_info() {
         Use given title as ani-skip query
       -N, --nextep-countdown
         Display a countdown to the next episode
-      -U, --update
-        Update the script
     Some example usages:
       %s -q 720p banana fish
       %s --skip --skip-title \"one piece\" -S 2 one piece
@@ -101,19 +99,23 @@ version_info() {
     exit 0
 }
 
-update_script() {
-    update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
-    update="$(printf '%s\n' "$update" | diff -u "$0" -)"
-    if [ -z "$update" ]; then
-        printf "Script is up to date :)\n"
-    else
-        if printf '%s\n' "$update" | patch "$0" -; then
-            printf "Script has been updated\n"
-        else
-            die "Can't update for some reason!"
-        fi
-    fi
-    exit 0
+# DEPRECATED: Self-updating via -U/--update flag has been removed.
+# Reason: This fork uses git for version control. Users should run 'git pull'
+# to update instead. Package manager users should use their package manager.
+# Original implementation (for reference only):
+#   update_script() {
+#       update="$(curl -s -A "$agent" "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
+#       update="$(printf '%s\n' "$update" | diff -u "$0" -)"
+#       if [ -z "$update" ]; then printf "Script is up to date :)\n"
+#       elif printf '%s\n' "$update" | patch "$0" -; then printf "Script has been updated\n"
+#       else die "Can't update for some reason!"; fi
+#       exit 0
+#   }
+_update_script_deprecated() {
+    printf "\33[2K\r\033[1;31mDEPRECATED: The -U/--update flag has been removed.\033[0m\n" >&2
+    printf "\033[1;33mFor git clones: Run 'git pull' in your ani-cli directory\033[0m\n" >&2
+    printf "\033[1;33mFor package installs: Use your package manager (apt/dnf/brew/etc.)\033[0m\n" >&2
+    exit 1
 }
 
 # checks if dependencies are present
@@ -487,7 +489,6 @@ while [ $# -gt 0 ]; do
             shift
             ;;
         -N | --nextep-countdown) search=nextep ;;
-        -U | --update) update_script ;;
         *) query="$(printf "%s" "$query $1" | sed "s|^ ||;s| |+|g")" ;;
     esac
     shift
